Evil_site/urls.py
#from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings
from django.views.generic.base import RedirectView
urlpatterns = [
	path("accounts/",include(("accounts.urls","accounts"),namespace="accounts")),
	path("music/",include(("music.urls","music"),namespace="music")),
	re_path(r"^.*$",RedirectView.as_view(pattern_name="accounts:accounts_register",permanent=False)),
	re_path(r"^static/(?P<path>.*)$", serve,{"document_root": settings.STATIC_ROOT}),
	#path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.accounts, name="accounts"),
	path("login", views.login, name="accounts_login"),
	path("register", views.register, name="accounts_register"),
]

music/urls.py
from django.urls import path
from . import views
app_name="music"
urlpatterns = [
	path("player", views.player, name="player"),
	path("upload", views.upload, name="upload"),
	path("musiclist", views.musiclist, name="musiclist"),
	path("addtomusiclist", views.addtomusiclist, name="addtomusiclist"),
	path("", views.music, name="music"),
]

templates/base.html
{% include "upper.html" %}

{{content}}

{% include "lower.html" %}

templates/lower.html
		</div>
		<br>
		<div id="footer" class="footer">
			&copy; TitanX(Гусев Сергей, email: sergey_gusev_007@mail.ru)
			<br>
			<a href="TERMS">Пользовательское соглашение</a>
			|
			<a href="PRIVACY">Политика конфиденциальности</a>
		</div>
	</body>
</html>

templates/player.html
{% load static %}
{% include "upper.html" %}
<link rel="stylesheet" href="{% static 'css/player.css' %}">
<div class="display">
	<div class="player">
		<!--div class="trackrange"></div-->
		<svg class="trackrange" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewbox="0 0 100 100">
			<circle id="full_arc" cx="50" cy="50" stroke-width="3" stroke="none" fill="none" r="48"/>
			<path id="arc" fill="none" stroke="#000000" stroke-width="3" stroke-linecap="round"/>
			<circle id="arc_pos" stroke-width="0.2" stroke="#ffffff" r="1"/>
		</svg>
		<svg class="skipleft-icon" onclick="skip(0)" width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path d="M90 54C92.2091 54 94 52.2091 94 50C94 47.7909 92.2091 46 90 46V54ZM7.17157 47.1716C5.60947 48.7337 5.60947 51.2663 7.17157 52.8284L32.6274 78.2843C34.1895 79.8464 36.7222 79.8464 38.2843 78.2843C39.8464 76.7222 39.8464 74.1895 38.2843 72.6274L15.6569 50L38.2843 27.3726C39.8464 25.8105 39.8464 23.2778 38.2843 21.7157C36.7222 20.1536 34.1895 20.1536 32.6274 21.7157L7.17157 47.1716ZM90 46L10 46V54L90 54V46Z" fill="currentColor"/>
			<rect x="1" y="1" width="98" height="98" rx="49" stroke="currentColor" stroke-width="2"/>
		</svg>
		
		<div class="image1">
			<svg xmlns="http://www.w3.org/2000/svg" class="icomp" style="color: var(--second-color); z-index: 0;" viewBox="-256 -256 1024 1024">
				<path d="M240 343.31V424a32.28 32.28 0 01-21.88 30.65l-21.47 7.23c-25.9 8.71-52.65-10.75-52.65-38.32h0A34.29 34.29 0 01167.25 391l50.87-17.12A32.29 32.29 0 00240 343.24V92a16.13 16.13 0 0112.06-15.66L360.49 48.2A6 6 0 01368 54v57.76a16.13 16.13 0 01-12.12 15.67l-91.64 23.13A32.25 32.25 0 00240 181.91v39.39" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/>
			</svg>
			<svg id="play" style="display: block; z-index: 1; position: absolute; top: 0;" xmlns="http://www.w3.org/2000/svg" class="icomp" viewBox="0 0 512 512">
				<path d="M112 111v290c0 17.44 17 28.52 31 20.16l247.9-148.37c12.12-7.25 12.12-26.33 0-33.58L143 90.84c-14-8.36-31 2.72-31 20.16z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/>
			</svg>
			<svg id="pause" style="display: none; z-index: 1; position: absolute; top: 0;" xmlns="http://www.w3.org/2000/svg" class="icomp" viewBox="0 0 512 512">
				<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M176 96h16v320h-16zM320 96h16v320h-16z"/>
			</svg>
		</div>
		
		<svg class="skipright-icon" onclick="skip(1)" width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path d="M92.8284 52.8284C94.3905 51.2663 94.3905 48.7337 92.8284 47.1716L67.3726 21.7157C65.8105 20.1536 63.2778 20.1536 61.7157 21.7157C60.1536 23.2778 60.1536 25.8105 61.7157 27.3726L84.3431 50L61.7157 72.6274C60.1536 74.1895 60.1536 76.7222 61.7157 78.2843C63.2778 79.8464 65.8105 79.8464 67.3726 78.2843L92.8284 52.8284ZM10 46C7.79086 46 6 47.7909 6 50C6 52.2091 7.79086 54 10 54V46ZM90 46L10 46V54L90 54V46Z" fill="currentColor"/>
			<rect x="1" y="1" width="98" height="98" rx="49" stroke="currentColor" stroke-width="2"/>
		</svg>
		<div class="text">
			<div class="title1" id="trackname">Title</div>
			<b class="author1" id="trackauthor">Author</b>
			<div class="time1" id="tracktime">0:00/0:00</div>
		</div>
		

		<div class="actions1">
			<svg class="add-icon" id="add_to_music" onclick="addtomusic(this)" width="46" height="46" viewBox="0 0 46 46" fill="none" xmlns="http://www.w3.org/2000/svg">
				<line x1="23" y1="36" x2="23" y2="10" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>
				<line x1="10" y1="23" x2="36" y2="23" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>
				<rect x="1" y="1" width="44" height="44" rx="21" stroke="currentColor" stroke-width="2"/>
			</svg>
			<svg class="add-icon" width="46" height="46" viewBox="0 0 46 46" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path d="M24.5 11C24.5 10.1716 23.8284 9.5 23 9.5C22.1716 9.5 21.5 10.1716 21.5 11H24.5ZM21.9393 36.0607C22.5251 36.6464 23.4749 36.6464 24.0607 36.0607L33.6066 26.5147C34.1924 25.9289 34.1924 24.9792 33.6066 24.3934C33.0208 23.8076 32.0711 23.8076 31.4853 24.3934L23 32.8787L14.5147 24.3934C13.9289 23.8076 12.9792 23.8076 12.3934 24.3934C11.8076 24.9792 11.8076 25.9289 12.3934 26.5147L21.9393 36.0607ZM21.5 11V35H24.5V11H21.5Z" fill="currentColor"/>
				<rect x="1" y="1" width="44" height="44" rx="21" stroke="currentColor" stroke-width="2"/>
			</svg>
		</div>

		<div class="settings">
			<svg class="add-icon" id="repeat_flag" width="46" height="46" viewBox="0 0 46 46" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path d="M11.5428 22.9218C12.1928 21.1358 13.3916 19.6015 14.9673 18.5387C16.5429 17.4759 18.4146 16.9392 20.3141 17.0055" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
				<path d="M20 17H31" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M28 14L31 17" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M28 20L31 17" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M33.4572 23.0782C32.8072 24.8642 31.6084 26.3985 30.0327 27.4613C28.4571 28.5241 26.5854 29.0608 24.6859 28.9945" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
				<path d="M25 29H14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M17 32L14 29" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M17 26L14 29" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<rect x="1" y="1" width="44" height="44" rx="21" stroke="currentColor" stroke-width="2"/>
				<circle cx="23" cy="23" id="for_repeat" stroke="currentColor" style="color: transparent;" r="19" stroke-width="2"/>
			</svg>
			<svg class="add-icon" id="shuffle_flag" width="46" height="46" viewBox="0 0 46 46" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path d="M10.2843 29.2961C10.9138 26.3355 12.5567 23.6874 14.9296 21.8084C17.3026 19.9293 20.2568 18.9372 23.2829 19.0031" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
				<path d="M23 19L32 19" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M29 16L32 19" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M29 22L32 19" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M10.2843 16.7039C10.9138 19.6645 12.5567 22.3126 14.9296 24.1916C17.3026 26.0707 20.2568 27.0628 23.2829 26.9969" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
				<path d="M23 27L32 27" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M29 30L32 27" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<path d="M29 24L32 27" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
				<rect x="1" y="1" width="44" height="44" rx="21" stroke="currentColor" stroke-width="2"/>
			</svg>
		</div>
		<input type="range" min="0" max="100" value="0" id="slider_range" class="volume_range">
		<ion-icon class="volume_icon" name="volume-high-outline"></ion-icon>
	</div>
	
	<label class="checkbox-green">
		<input type="radio" id="MyMusic" name="MyMusic" onclick="load_tracklist()" value="true" checked />
		<label for="MyMusic">Моя музыка</label>
			<input type="radio" id="AllMusic" name="MyMusic" onclick="load_tracklist()" value="false" />
		<label for="AllMusic">Вся музыка</label>
	</label>
	
	<div class="playlist"  id="MusicList_box">
	</div>
	
</div>
<script src="{% static 'scripts/player.js' %}"></script>

{% include "lower.html" %}

templates/register.html
{% include "upper.html" %}
<script type="text/javascript">
	function REGISTER() {
		$.ajax({
			url: "{% url 'accounts:accounts_register' %}",
			type: "POST",
			beforeSend: function(request) {
				request.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
			},
			mode: "same-origin",
			data: {
					"name": document.getElementById("reg_name").value,
					"lastname": document.getElementById("reg_lastname").value,
					"login": document.getElementById("reg_login").value,
					"email": document.getElementById("reg_email").value,
					"password": document.getElementById("reg_password").value,
					"birth_date": document.getElementById("reg_birth_date").value
				},
			dataType: "json",
			success: function(response) {
				document.getElementById("output").innerHTML=response.message;
			},
			error: function(response) {
				console.log("Error on login and info_catch:",response);
			}
		});
	}
</script>
<div class="dropdown_reg" id="output">
	<form action="javascript:REGISTER()" method="POST" accept-charset="UTF-8">
		<h2>Регистрация</h2>
		<br>
		<div class="input-box">
			<input type="text" id="reg_name" autocomplete="name" minlength="2" maxlength="64" value="" required>
			<label for="reg_name">Имя</label>
		</div>
		<br>
		<div class="input-box">
			<input type="text" id="reg_lastname" autocomplete="family-name" minlength="2" maxlength="64" value="" required>
			<label for="reg_lastname">Фамилия</label>
		</div>
		<br>
		<div class="input-box">
			<input type="text" id="reg_login" minlength="2" autocomplete="username" maxlength="64" value="" required>
			<label for="reg_login">Логин</label>
		</div>
		<br>
		<div class="input-box">
			<span class="icon"><ion-icon name="mail"></ion-icon></span>
			<input type="text" id="reg_email" autocomplete="email" minlength="2" maxlength="127" value="" required>
			<label for="reg_email">Email</label>
		</div>
		<br>
		<div class="input-box">
			<span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
			<input type="password" id="reg_password" autocomplete="new-password" minlength="12" maxlength="255" value="" required>
			<label for="reg_password">Пароль</label>
		</div>
		<br>
		<div class="input-box" style="border: none;">
			<label for="reg_birth_date" style="top: -2vh;">Дата рождения</label>
			<input type="date" id="reg_birth_date" autocomplete="bday" required>
		</div>
		<div class="reg_gender_style">
			<label for="reg_gender" style="font-size: 2em; font-weight: 400;">Пол:</label>
			<br>
			<input type="radio" id="reg_gender" name="reg_gender" value="Мужчина" checked>
			<label for="reg_gender" style="font-size: 1.6em;">Мужчина</label>
			<br>
			<input type="radio" id="Femail" name="reg_gender" value="Женщина">
			<label for="Femail" style="font-size: 1.6em;">Женщина</label>
			<br>
		</div>
		<br>
		<input type="submit" value="Создать аккаунт" class="login-btn">
	</form>
</div>
<!-- class="input-box-checkbox"-->
{% include "lower.html" %}

templates/upload_track.html
{% include "upper.html" %}
<script type="text/javascript">
	async function UPLOAD() {
		let data = new FormData();

		data.append("title", document.getElementById("track_title").value);
		data.append("author", document.getElementById("track_author").value);
		let value_input = document.getElementById("track_file").files;
		if(!value_input.length) return false;

		data.append("file", value_input[0]);

		close = await fetch("{% url 'music:upload' %}", {
			method: "POST",
			credentials: "include",
			headers: {
				"X-CSRFToken": getCookie("csrftoken"),
			},
			mode: "same-origin",
			body: data,
		}).then((response) => response.json())
		.then((response) => {
			document.getElementById("output").innerHTML=response.message;
			return true;
		})
		.catch((err) => {
			console.log("Error on login and info_catch:",response);
			return false;
		})
	}
</script>
<div class="dropdown_reg" id="output">
	<form action="javascript:UPLOAD()" method="POST" accept-charset="UTF-8">
		<h2>Добавить трек</h2>
		<br>
		<div class="input-box">
			<input type="text" id="track_title" autocomplete="none" minlength="1" maxlength="64" value="" required>
			<label for="track_title">Название</label>
		</div>
		<br>
		<div class="input-box">
			<input type="text" id="track_author" autocomplete="none" minlength="1" maxlength="64" value="" required>
			<label for="track_author">Автор</label>
		</div>
		<br>
		<div class="input-box">
			<label for="track_file" style="top: -2vh;">Файл</label>
			<input type="file" accept=".mp3" id="track_file" required>
		</div>
		<br>
		<input type="submit" value="Добавить" class="login-btn">
	</form>
</div>
<!-- class="input-box-checkbox"-->
{% include "lower.html" %}

templates/upper.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
	<head>
		<!--meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"-->
		<meta name="Description" content="Evil">
		<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
		<title>Evil</title>
		<link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
		<script src="{% static 'scripts/jquery.min.js' %}" type="text/javascript"></script>
		<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
		<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
		<script>
			var LOGIN_URL="{% url 'accounts:accounts_login' %}";
			var ACCOUNTS_URL="{% url 'accounts:accounts' %}";
			var LOAD_MUSIC_URL="{% url 'music:music' %}";
			var LOAD_MUSICLIST_URL="{% url 'music:musiclist' %}";
			var ADD_TO_MUSICLIST_URL="{% url 'music:addtomusiclist' %}";
		</script>
		<script src="{% static 'scripts/Base.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>
	<body>
		<div class="topnav">
			<svg width="130" height="130" viewBox="0 0 130 130" fill="none" class="logo" style="padding-left: 8px; padding-right: 0px;" stroke="currentColor" xmlns="http://www.w3.org/2000/svg">
				<path d="M105 19V60" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M15 92L27 87" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
				<path d="M25 19L45 40" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M25 19L25 59" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M15 65L27 74" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
				<path d="M45 59V70" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
				<path d="M118 65L106 74" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
				<path d="M60 89H71" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M30 101L39.625 111L64.5625 111L90.375 111L100 101" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M118 92L106 87" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M85 59V70" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
				<path d="M105 19L85 40" stroke="currentColor" stroke-width="5" stroke-linecap="round"/>
				<path d="M53 40L77 40" stroke="currentColor" stroke-width="6" stroke-linecap="round"/>
			</svg>
			<div class="logo">Evil</div>
			<a href="{% url 'music:player' %}">Музыка</a>
			<a href="{% url 'music:upload' %}">Загрузить</a>

			<span class="dropbtn" alt="Account" onclick="DROP()"><ion-icon name="person-circle"></ion-icon></span>
			<span class="dropbtn" onclick="changeTheme()"><ion-icon name="sunny-outline" id="sun-changeTheme" ></ion-icon><ion-icon name="moon-outline" id="moon-changeTheme"></ion-icon></span>
		</div>
		<div id="AccountDropdown" class="dropdown">
			<div id="login_form">
				<form action="javascript:LOGIN()" method="POST">{% csrf_token %}
					<h2>Вход</h2>
					<div class="input-box">
						<span class="icon"><ion-icon name="mail"></ion-icon></span>
						<input type="text" name="EMAIL" id="EMAIL_form" value="" autocomplete="true" required>
						<label for="EMAIL_form">Логин/Email</label>
					</div>
					<br>
					<div class="input-box">
						<span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
						<input type="password" name="PASSWORD" id="PASSWORD_form" value="" autocomplete="true" required>
						<label for="PASSWORD_form">Пароль</label>
					</div>
					<br>
					<input type="submit" value="Вход" class="login-btn">
					<div class="login-register">
						<p>Ещё не создали аккаунт?<a href="{% url 'accounts:accounts_register' %}" class="register-link"> Зарегистрироваться</a></p>
					</div>
				</form>
			</div>
			<div id="account_info" class="account">
				<div class="big-text" id="name">name</div>
				<a href="{% url 'accounts:accounts' %}" id="login-href" style="text-decoration: none;">
					<div class="big-text" id="login">login</div>
				</a>
				<br>
				<div class="exit_btn" onclick="EXIT()">
					<div class="like_label">Выход</div>
					<span class="icon"><ion-icon name="exit-outline"></ion-icon></span>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			document.getElementById("account_info").style.display="none";
			LOGIN();
			changeTheme(localStorage.getItem("theme")=="dark");
		</script>
		<div class="big-text" id="content_data">